name: Build Docker Dev Server

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check HOST
      run: echo ${{ secrets.HOST_DEV }}

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST_DEV }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd ${{ secrets.SSH_PATH }}
          docker compose --env-file .env up --build -d
